name: 🐞 Bug Report
description: Create a bug report
labels: ["bug"]
body:
  - type: dropdown
    attributes:
      label: Describe the Bug
      description: Include the steps to reproduce this bug if applicable.
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Where are you running VSCode? (Optional)
      options:
        - Windows
        - MacOS
        - Linux
        - Browser
    validations:
      required: false
  - type: dropdown
    attributes:
      label: Which OpenAI model are you using? (Optional)
      description: In the model dropdown, do you have "gpt-3.5-turbo", "gpt-4", or "gpt-4-32k" selected?
      options:
        - gpt-3.5-turbo
        - gpt-4
        - gpt-4-32k
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional context (Optional)
      description: Add any other context about the problem here. Please provide screenshots or screen recordings if possible.
    validations:
      required: false
